#!/usr/bin/env python3
"""Git merge driver for the committed state in data/.

The poller commits data/ on every sweep, about once a minute, so any branch
that lives longer than a minute conflicts with master on files no human ever
edits. Resolving those by hand is busywork, and resolving them by picking a
side is wrong: data/seen.json is what stops a role being pushed to the phone
twice, so dropping the uids one side had already notified re-notifies them.

A `union` merge, which is git's usual answer for append-only files, cannot be
used here. These are JSON documents, and union concatenates the conflicting
lines from both sides, which produces a file the poller cannot parse.

So each file is merged on its own terms, exactly as they were resolved by hand
once before:

    seen.json      union of uids, earliest first-seen wins
    slugs.json     union of boards, a deliberate origin never downgraded
    jobs.json      union by uid, ours winning on a tie
    closures.json  concatenated, exact repeats dropped
    anything else  ours

IMPORTANT: a custom merge driver runs on the machine doing the merge. GitHub's
own merge button does not run it, so a pull request can still show a conflict
on github.com even with this installed. It is for merging locally, which is
where these conflicts are actually resolved.

Install (once per clone, because a driver cannot be defined in .gitattributes):

    git config merge.jobstate.name "job watcher state merge"
    git config merge.jobstate.driver "python3 tools/merge-state.py %O %A %B %P"

Git calls it as:  merge-state.py <ancestor> <ours,dest> <theirs> <path>
It must leave the merged result in <ours> and exit 0.
"""

import json
import os
import sys
import time


def read(path):
    try:
        with open(path, encoding="utf-8") as fh:
            return json.load(fh)
    except Exception:  # noqa: BLE001 - an unreadable side is treated as absent
        return None


def write(path, payload):
    with open(path, "w", encoding="utf-8") as fh:
        json.dump(payload, fh, indent=1, sort_keys=True)
        fh.write("\n")


def merge_seen(ours, theirs):
    """Union the uids, keeping the earliest first-seen for each.

    This is the file that stops a role being pushed twice. Losing a uid means
    the next sweep treats an old role as new and sends it to the phone again.
    """
    merged = dict((theirs or {}).get("uids", {}))
    for uid, at in (ours or {}).get("uids", {}).items():
        merged[uid] = min(at, merged.get(uid, at))
    return {"count": len(merged), "uids": merged}


def merge_slugs(ours, theirs):
    """Union the board registry.

    A board with a "config" or "hunted-ca" origin was added deliberately and is
    polled every sweep, so it must not be overwritten by the other side's
    "discovered" entry for the same slug, which would demote it into rotation.
    """
    merged = {}
    for side in (theirs, ours):
        for source, block in ((side or {}).get("sources") or {}).items():
            dest = merged.setdefault(source, {})
            for slug, entry in block.items():
                if dest.get(slug, {}).get("origin") in ("config", "hunted-ca"):
                    continue
                dest[slug] = entry
    return {
        "count": sum(len(v) for v in merged.values()),
        "sources": merged,
        "updated_at": int(time.time()),
    }


def merge_jobs(ours, theirs):
    """Union by uid, ours winning.

    A union rather than a choice, so no role disappears at the moment of a
    merge, including one that was pushed to the phone from the other side.
    """
    merged = {j["uid"]: j for j in (theirs or {}).get("jobs", []) if j.get("uid")}
    merged.update({j["uid"]: j for j in (ours or {}).get("jobs", []) if j.get("uid")})
    rows = list(merged.values())
    return {"generated_at": int(time.time()), "count": len(rows), "jobs": rows}


def merge_closures(ours, theirs):
    """A log. Concatenate and drop exact repeats."""
    rows, seen = [], set()
    for row in ((theirs or {}).get("closed", []) + (ours or {}).get("closed", [])):
        key = (row.get("uid"), row.get("closed_at"))
        if key in seen:
            continue
        seen.add(key)
        rows.append(row)
    return {"closed": rows}


MERGERS = {
    "seen.json": merge_seen,
    "slugs.json": merge_slugs,
    "jobs.json": merge_jobs,
    "closures.json": merge_closures,
}


def main(argv):
    if len(argv) < 4:
        return 1
    _ancestor, ours_path, theirs_path, path = argv[0], argv[1], argv[2], argv[3]

    merger = MERGERS.get(os.path.basename(path))
    if merger is None:
        # health.json and anything else: keep ours. It is regenerated by the
        # next sweep, and the only cost of the wrong ETags is one full fetch.
        return 0

    ours, theirs = read(ours_path), read(theirs_path)
    if ours is None and theirs is None:
        # Neither side parses. Fail the merge rather than write something the
        # poller cannot read.
        return 1
    if ours is None:
        ours = theirs
    if theirs is None:
        theirs = ours

    write(ours_path, merger(ours, theirs))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
